### ISSUE TITLE
Online demo is broken.

### ISSUE THREAD

**Issue by audreytoskin** [marytts/marytts.github.io#1]
The site has a link to a demo -- http://mary.dfki.de:59125/

The page never loads. When I try it using Firefox 40, it says "Unable to Connect." When I try it with Chrome 45, it says "This webpage is not available. ERR_CONNECTION_REFUSED"

I'm running Fedora 22 (64-bit), and have had no other networking issues all day.

**Comment by psibre** [comment]
Actually, it has nothing to do with this repository. However, it did draw our attention to the fact that the server restart after a data center outage had not restarted the MaryTTS demo... so thanks for the report!

Fixed now, but at risk (see [my recent message to the mailing list](http://www.dfki.de/pipermail/mary-users/2015-September/001751.html)).

**Comment by audreytoskin** [comment]
I actually had started to wonder if maybe the demo had been discontinued, so I thought I was more reporting a dead link.

If the demo's back online, that's good too. :)
